apiVersion: v1
kind: Secret
metadata:
  name: slack-bot-secrets
type: Opaque
data:
  # Base64 encoded values - replace with your actual base64 encoded secrets
  # To encode: echo -n "your-secret" | base64
  openai-api-key: <base64-encoded-openai-api-key>
  openai-assistant-id: <base64-encoded-openai-assistant-id>
  slack-bot-token: <base64-encoded-slack-bot-token>
  slack-signing-secret: <base64-encoded-slack-signing-secret> 